CREATE TABLE stg_fec_candidate_contrib_comm (
CMTE_ID VARCHAR(9) NOT NULL,
AMNDT_IND VARCHAR(1),
RPT_TP VARCHAR(3),
TRANSACTION_PGI VARCHAR(5),
IMAGE_NUM VARCHAR(11),
TRANSACTION_TP VARCHAR(3),
ENTITY_TP VARCHAR(3),
NAME VARCHAR(200),
CITY VARCHAR(30),
STATE VARCHAR(2),
ZIP_CODE VARCHAR(9),
EMPLOYER VARCHAR(38),
OCCUPATION VARCHAR(38),
TRANSACTION_DT VARCHAR(10),
TRANSACTION_AMT DECIMAL(14,2),
OTHER_ID VARCHAR(9),
CAND_ID VARCHAR(9),
TRAN_ID VARCHAR(32),
FILE_NUM INTEGER(14),
MEMO_CD VARCHAR(1),
MEMO_TEXT VARCHAR(100),
SUB_ID INTEGER(19)
);

CREATE TABLE master_source_download (
SOURCE_ENTITY VARCHAR(25) NOT NULL,
SOURCE_URL VARCHAR(500) NOT NULL,
SOURCE_FILE_TYPE VARCHAR(25) NOT NULL,
TARGET_TABLE VARCHAR(500) NOT NULL,
SOURCE_ACTIVE TINYINT(1) NOT NULL DEFAULT 0,
DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ELECTION_CYCLE VARCHAR(10) NOT NULL,
DATA_LOADER_CLASS VARCHAR(200) NOT NULL,
ADDED_BY VARCHAR(25)
);

update master_source_download SET SCHEDULED_LOAD_TIME = '01:45:00';

insert into master_source_download (SOURCE_ENTITY, SOURCE_URL, TARGET_TABLE, SOURCE_ACTIVE, 
	DATE_ADDED, ADDED_BY, ELECTION_CYCLE, SOURCE_FILE_TYPE, DATA_LOADER_CLASS, SCHEDULED_LOAD_TIME, 
	DELIMITER) 
VALUES ('FEC', 'ftp://ftp.fec.gov/FEC/2004/pas204.zip', 'stg_fec_candidate_contrib_comm', 1, 
	'2014-09-12 21:39', 'DYMEKC', '2003-2004', 'zip', 'com.MyRepMoney.dataloader.FECDataLoader', '', 
	'|');